// <auto-generated />
namespace Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phienban1_TaoBang_Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phienban1_TaoBang_Products));
        
        string IMigrationMetadata.Id
        {
            get { return "201903121014279_phienban1_TaoBang_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
