// <auto-generated />
namespace Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phienban0_TaoBang_Categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phienban0_TaoBang_Categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201903120952475_phienban0_TaoBang_Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
