// <auto-generated />
namespace Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create2spthongke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create2spthongke));
        
        string IMigrationMetadata.Id
        {
            get { return "201904051545030_create 2 spthongke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
